name: Terraform CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  global:
    uses: ./.github/workflows/terraform.yml
    with:
      terraform_version: '1.8.3'
      configuration_name: 'global'
