name: Terraform

on:
  workflow_call:
    inputs:
      terraform_version:
        description: "Terraform version to be tested"
        required: false
        type: string
        default: '1.8.3'
      configuration_name:
        description: "Name of the configuration/environment/application"
        required: true
        type: string
      backend_config:
        description: "Which backend should be evaluated"
        required: true
        type: string


jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Assume IAM role
      id: assume-role
      uses: aws-actions/aws-assume-role@v1
      with:
        role-arn: arn:aws:iam::123456789012:role/YourIAMRole
        role-session-name: GitHubActionsSession

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Terraform Init
      env:
        AWS_ACCESS_KEY_ID: ${{ steps.assume-role.outputs.access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ steps.assume-role.outputs.secret-access-key }}
        AWS_SESSION_TOKEN: ${{ steps.assume-role.outputs.session-token }}
      working-directory: ./
      run: terraform init -backend-config=backend/${{ inputs.configuration_name }}.tfvars

    - name: Terraform Format
      working-directory: ./
      run: terraform fmt -check

    - name: Terraform Validate
      env:
        AWS_ACCESS_KEY_ID: ${{ steps.assume-role.outputs.access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ steps.assume-role.outputs.secret-access-key }}
        AWS_SESSION_TOKEN: ${{ steps.assume-role.outputs.session-token }}
      working-directory: ./
      run: terraform validate
